void lemon(){
tone(loudspeaker_pin, 554);
delay(base_time / 16);
tone(loudspeaker_pin, 622);
delay(base_time / 16);
tone(loudspeaker_pin, 554);
delay(base_time / 16);
tone(loudspeaker_pin, 494);
delay(base_time / 16);
tone(loudspeaker_pin, 415);
delay(base_time / 8);
tone(loudspeaker_pin, 494);
delay(base_time * 3 / 2 / 8);
tone(loudspeaker_pin, 622);
delay(base_time / 8);
tone(loudspeaker_pin, 740);
delay(base_time * 3 / 2 / 8);
tone(loudspeaker_pin, 554);
delay(base_time / 8);
tone(loudspeaker_pin, 494);
delay(base_time * 3 / 2 / 8);
tone(loudspeaker_pin, 554);
delay(base_time / 16);
tone(loudspeaker_pin, 622);
delay(base_time / 16);
tone(loudspeaker_pin, 554);
delay(base_time / 16);
tone(loudspeaker_pin, 494);
delay(base_time / 16);
tone(loudspeaker_pin, 415);
delay(base_time / 8);
tone(loudspeaker_pin, 494);
delay(base_time * 3 / 2 / 8);
tone(loudspeaker_pin, 622);
delay(base_time / 8);
tone(loudspeaker_pin, 740);
delay(base_time * 3 / 2 / 8);
tone(loudspeaker_pin, 554);
delay(base_time / 8);
tone(loudspeaker_pin, 494);
delay(base_time * 3 / 2 / 8);
tone(loudspeaker_pin, 554);
delay(base_time / 16);
tone(loudspeaker_pin, 622);
delay(base_time / 16);
tone(loudspeaker_pin, 554);
delay(base_time / 16);
tone(loudspeaker_pin, 494);
delay(base_time / 16);
tone(loudspeaker_pin, 415);
delay(base_time / 8);
tone(loudspeaker_pin, 494);
delay(base_time * 3 / 2 / 8);
tone(loudspeaker_pin, 622);
delay(base_time / 8);
//tone(loudspeaker_pin, 740);
//delay(base_time / 4);
tone(loudspeaker_pin, 740);
delay(base_time / 8);
tone(loudspeaker_pin, 831);
delay(base_time / 8);
tone(loudspeaker_pin, 740);
delay(base_time * 3 / 2 / 8);
//tone(loudspeaker_pin, 740);
//delay(base_time / 8);
tone(loudspeaker_pin, 988);
delay(base_time * 3 / 2 / 8);
tone(loudspeaker_pin, 932);
delay(base_time / 8);
tone(loudspeaker_pin, 740);
delay(base_time * 3 / 2 / 8);
tone(loudspeaker_pin, 622);
delay(base_time / 8);
tone(loudspeaker_pin, 740);
delay(base_time / 4);
tone(loudspeaker_pin, 554);
delay(base_time * 3 / 2 / 8);
}
